CREATE RESOURCE MONITOR IF NOT EXISTS INSIGHT_AGENT_RM
  WITH
    CREDIT_QUOTA = 50                    -- 50 credits/month total
    FREQUENCY = MONTHLY
    START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 75  PERCENT DO NOTIFY
    ON 90  PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND
    ON 110 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE INSIGHT_AGENT_WH     SET RESOURCE_MONITOR = INSIGHT_AGENT_RM;
ALTER WAREHOUSE INSIGHT_AGENT_APP_WH SET RESOURCE_MONITOR = INSIGHT_AGENT_RM;
