-- Give yourself the admin role
GRANT ROLE INSIGHT_AGENT_ADMIN TO USER naveenkumar1989;

-- Create a stage for semantic model YAML files
USE ROLE INSIGHT_AGENT_ADMIN;
USE DATABASE INSIGHT_AGENT_DB;
USE SCHEMA METADATA;

CREATE STAGE IF NOT EXISTS SEMANTIC_MODELS
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  COMMENT = 'Versioned semantic model YAMLs';

-- Verify
SHOW STAGES IN SCHEMA METADATA;
