-- Cortex access (required for Analyst, Search, Complete)
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE INSIGHT_AGENT_USER;

-- Warehouse usage
GRANT USAGE ON WAREHOUSE INSIGHT_AGENT_WH     TO ROLE INSIGHT_AGENT_USER;
GRANT USAGE ON WAREHOUSE INSIGHT_AGENT_APP_WH TO ROLE INSIGHT_AGENT_USER;

-- Database and schema usage (all roles need to see the structure)
GRANT USAGE ON DATABASE INSIGHT_AGENT_DB TO ROLE INSIGHT_AGENT_USER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE INSIGHT_AGENT_DB TO ROLE INSIGHT_AGENT_USER;

-- Source data (TPCH sample) — SELECT on all tables
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_SAMPLE_DATA TO ROLE INSIGHT_AGENT_USER;

-- Dev needs to create objects in the agent DB
GRANT CREATE VIEW, CREATE STAGE, CREATE TABLE, CREATE STREAMLIT, 
      CREATE CORTEX SEARCH SERVICE, CREATE AGENT
  ON SCHEMA INSIGHT_AGENT_DB.CURATED     TO ROLE INSIGHT_AGENT_DEV;
GRANT CREATE STAGE, CREATE TABLE
  ON SCHEMA INSIGHT_AGENT_DB.METADATA    TO ROLE INSIGHT_AGENT_DEV;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA INSIGHT_AGENT_DB.OBSERVABILITY TO ROLE INSIGHT_AGENT_DEV;
GRANT CREATE STREAMLIT, CREATE AGENT, CREATE CORTEX SEARCH SERVICE
  ON SCHEMA INSIGHT_AGENT_DB.APP         TO ROLE INSIGHT_AGENT_DEV;

-- Admin gets everything the dev has, plus ownership
GRANT OWNERSHIP ON DATABASE INSIGHT_AGENT_DB TO ROLE INSIGHT_AGENT_ADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON ALL SCHEMAS IN DATABASE INSIGHT_AGENT_DB TO ROLE INSIGHT_AGENT_ADMIN COPY CURRENT GRANTS;
GRANT MONITOR, OPERATE ON WAREHOUSE INSIGHT_AGENT_WH     TO ROLE INSIGHT_AGENT_ADMIN;
GRANT MONITOR, OPERATE ON WAREHOUSE INSIGHT_AGENT_APP_WH TO ROLE INSIGHT_AGENT_ADMIN;
